-- GENERATED FILE: review source provenance and content before applying.
-- Content is unpublished unless --publish was explicitly used.

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-299755eb135c', 'en', 'A1', 'Meet Lucas and His Family', 'Meet my family. I am Lucas. I am 25 years old. This is my mother. She is a doctor. My father is an engineer. He works in a hospital. My sister is a student. She is 20. We live in São Paulo. We are a happy family. My mother is very smart. My father is very funny. My sister is very nice.

My brother is not here. He is in Rio. He is a musician. They are my grandparents. They live with us. They are very kind. You can visit us. You are welcome! Our house is big. It has a garden. We love our home.', '[{"answer_index":0,"explanation_pt_br":"No texto, lemos: ''This is my mother. She is a doctor.'' Portanto, a mãe de Lucas é médica.","options":["Lucas''s mother","Lucas''s father","Lucas''s sister","Lucas"],"prompt":"Who is a doctor?"},{"answer_index":0,"explanation_pt_br":"O texto diz: ''My father is an engineer. He works in a hospital.''","options":["In a hospital","In a school","In a garden","In Rio"],"prompt":"Where does Lucas''s father work?"},{"answer_index":0,"explanation_pt_br":"''They'' refere-se a ''my grandparents'' na frase anterior: ''They are my grandparents.''","options":["Lucas''s grandparents","Lucas''s parents","Lucas''s friends","Lucas''s teachers"],"prompt":"In the text, ''They are very kind.'' What does ''They'' refer to?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-4a821f6c4618', 'en', 'A1', 'My Friends and I', 'Hello! My name is Ana. I am from Brazil. I am a student. This is my friend Carlos. He is also a student. He likes to read books. This is his sister, Beatriz. She is a nurse. She works at a hospital. She is very kind.

We are at the park today. You are with us. It is a beautiful day. The sun is hot. The park has many trees. A small dog is near us. It is brown and white. We like the dog very much.

They are our neighbors. They live near my house. They have two children. The children are very young. We talk to them every week. I am happy because we are all friends. You are important to me. We are a happy group!', '[{"answer_index":1,"explanation_pt_br":"Ana é uma mulher, então usamos o pronome ''she'' (ela).","options":["I","She","He","It"],"prompt":"Which subject pronoun can replace the name ''Ana'' in the text?"},{"answer_index":1,"explanation_pt_br":"O pronome ''we'' (nós) é usado para um grupo que inclui quem fala.","options":["They","We","You","It"],"prompt":"Which subject pronoun is used to talk about a group of people including the speaker?"},{"answer_index":2,"explanation_pt_br":"Usamos ''it'' para animais e objetos.","options":["He","She","It","They"],"prompt":"In the sentence ''___ is brown and white.'', which pronoun correctly refers to the dog?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-9fe62cbe5a25', 'en', 'A1', 'Meet Luiza and Her Friends', 'Hello! My name is Luiza. I am from Brazil. I am a student. This is my friend Tom. He is from England. He is a teacher. This is Maria. She is my sister. She is a doctor. We are in São Paulo today. We are happy.

Look at the dog! It is small. It is cute. It is our dog, Bidu. You are my new classmate. Are you from Brazil? Yes, you are. You are very nice. They are my parents, Mr. and Mrs. Souza. They are very kind. They are on vacation.

We are all together now. I am very happy. You are my friend. He is a good teacher. She is a great doctor. It is a beautiful day. We are one big family. They are our neighbors. Goodbye!', '[{"answer_index":1,"explanation_pt_br":"Tom é um homem. Em inglês, usamos o pronome ''he'' (ele) para homens. O texto diz: ''He is a teacher.''","options":["She","He","It","You"],"prompt":"What pronoun do we use for Tom?"},{"answer_index":1,"explanation_pt_br":"Maria é uma mulher. Usamos o pronome ''she'' (ela) para mulheres. O texto diz: ''She is a doctor.''","options":["He","She","It","They"],"prompt":"What pronoun do we use for Maria?"},{"answer_index":2,"explanation_pt_br":"Para animais e coisas, usamos o pronome ''it'' (ele/ela, neutro). O texto diz: ''It is small.''","options":["He","She","It","We"],"prompt":"What pronoun do we use for the dog?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-6d95c84818ff', 'en', 'A1', 'My Friends and I', 'Hello! My name is Ana. I am from Brazil. This is my friend John. He is from the USA. She is Maria. She is my sister. We are students. You are a teacher. They are our dogs. It is a cat.

We are in a park. The park is big. It is beautiful. I am happy. John and Maria are happy too. They are my best friends. We like to play soccer. You can play with us. Are you ready? Yes, we are!

This is our school. It is near the park. Our teacher is Mr. Smith. He is very kind. She is Mrs. Brown. She is English. They are our classmates. We are a team.', '[{"answer_index":0,"explanation_pt_br":"''They'' é o pronome da terceira pessoa do plural, usado para pessoas ou coisas. No texto, refere-se aos cachorros: ''Eles são nossos cachorros.''","options":["Eles/Elas","Nós","Vocês","Ele"],"prompt":"What does ''They'' mean in the text: ''They are our dogs.''?"},{"answer_index":0,"explanation_pt_br":"O pronome ''We'' (nós) concorda com o verbo ''are''. As outras opções são singulares e usam ''is''.","options":["We","She","He","It"],"prompt":"Complete: ''___ are students.''"},{"answer_index":0,"explanation_pt_br":"''She'' refere-se a Maria, porque estamos falando de uma pessoa do gênero feminino.","options":["Maria","Ana","John","The park"],"prompt":"In ''She is Maria. She is my sister.'', what does ''She'' refer to?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-fe7cefb9642c', 'en', 'A1', 'My Friends and I', 'I am Ana, and this is my friend Paul. He is from England. He is a teacher. She is Maria, my sister. She is a nurse. We are in a big city. It is very beautiful. You are welcome here.

My classmates are from many countries. They are very friendly. We are happy together. Paul is an English teacher, and Maria is a nurse. I am a student. We are not from the same city, but we are friends. Are you a student too? I think you are.

Today we are at a café. It is small but nice. We are very happy. This is our first meeting. You are our new friend. Welcome!', '[{"answer_index":1,"explanation_pt_br":"O texto diz: ''He is from England.'' O pronome ''He'' refere-se a Paul, então Paul é da Inglaterra.","options":["Ana","Paul","Maria","We"],"prompt":"Who is from England?"},{"answer_index":2,"explanation_pt_br":"No texto: ''She is a nurse.'' ''She'' refere-se a Maria. Portanto, Maria é enfermeira.","options":["She is a teacher.","She is a student.","She is a nurse.","She is a doctor."],"prompt":"What does Maria do?"},{"answer_index":0,"explanation_pt_br":"No último parágrafo, ''we'' se refere a Ana, Paul e Maria. Eles estão em um café. ''You'' é a pessoa a quem eles dão as boas-vindas.","options":["Ana, Paul and Maria","Only Ana","The classmates from many countries","You"],"prompt":"Who is at the café in the last paragraph?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-845b8f2e8367', 'en', 'A1', 'My Friends and Family', 'Hello! My name is Ana. I am from Brazil. I am a teacher. This is my friend John. He is from the United States. He is a doctor. That is Maria. She is from Portugal. She is a student. We are in São Paulo. We are happy. My friends are very nice.

My family is here too. My parents are Carlos and Beatriz. They are from Rio de Janeiro. They are retired. This is my dog, Bidu. It is small and friendly. My brother Pedro is a chef. He is very tall. My sister Carla is a nurse. She is short. We are all together today. My family is big and fun.

You are my new friend. You are welcome here! Are you excited? I am excited. Today is a special day for us. We have a party. The party is for the family. Everything is ready. We are ready!', '[{"answer_index":1,"explanation_pt_br":"No texto, John é médico: \"He is a doctor.\"","options":["He is a teacher","He is a doctor","He is a chef","He is a nurse"],"prompt":"Who is John?"},{"answer_index":0,"explanation_pt_br":"Carla é enfermeira: \"My sister Carla is a nurse.\"","options":["She is a nurse","She is a student","She is a doctor","She is a chef"],"prompt":"Who is Carla?"},{"answer_index":2,"explanation_pt_br":"A festa está acontecendo: \"We have a party. The party is for the family.\"","options":["They are working","They are happy","They are having a party","They are traveling"],"prompt":"What are they doing today?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-9d6c53952f78', 'en', 'A1', 'My New Friends', 'I am Ana, and I am from Brazil. I live in São Paulo with my family. My father is a teacher. He is very patient. My mother is a nurse. She is kind and beautiful. I have a brother. He is fifteen years old. I also have a sister. She is a student.

We are a happy family. My friends are interesting. John is from Canada. He is an engineer. Maria is from Portugal. She is a doctor. They are in my English class. We are classmates. You are here too! I think you are a nice person.

Our teacher is Mr. Smith. He is from the United States. He is funny and smart. We are learning English together. It is a new language for us. I am excited, and we are ready to learn.', '[{"answer_index":0,"explanation_pt_br":"No texto, Ana diz: \"I am from Brazil.\" Portanto, ela é do Brasil.","options":["Brazil","Portugal","Canada","United States"],"prompt":"Where is Ana from?"},{"answer_index":1,"explanation_pt_br":"O texto diz: \"Maria is from Portugal. She is a doctor.\" Então Maria é médica.","options":["She is a teacher.","She is a doctor.","She is a nurse.","She is an engineer."],"prompt":"What does Maria do?"},{"answer_index":3,"explanation_pt_br":"John e Maria são duas pessoas, então usamos o pronome ''they'' (eles/elas).","options":["He","She","We","They"],"prompt":"Which pronoun can replace ''John and Maria'' in the sentence ''John and Maria are in my English class''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-2b41e01a20c7', 'en', 'A1', 'Our New Friends', 'Hello! My name is Ana. I am from Brazil. This is my friend, Paul. He is from the United States. She is Maria. She is a teacher. We are students at an English school. You are welcome to join us!

Our teachers are Mr. Smith and Ms. Jones. They are very nice. The school is big. It is near the park. We have class every day. Today, we are happy because it is Friday!

Paul is an engineer. He works with computers. Maria has a son. His name is Pedro. He is six years old. Pedro and I are friends. They are a happy family. Are you ready to learn?', '[{"answer_index":0,"explanation_pt_br":"Maria é uma mulher (ela), então usamos o pronome ''she''.","options":["She","He","It","They"],"prompt":"Which pronoun can replace ''Maria''?"},{"answer_index":2,"explanation_pt_br":"Pedro and I = nós (we), e com ''we'' usamos ''are''.","options":["is","am","are","be"],"prompt":"Complete: ''Pedro and I ___ friends.''"},{"answer_index":1,"explanation_pt_br":"Com o pronome ''you'', o verbo ''be'' sempre é ''are''.","options":["You is ready.","You are ready.","You am ready.","You be ready."],"prompt":"Choose the correct sentence."}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-cc7e716e50a6', 'en', 'A1', 'My Friends and I', 'Hello! My name is Ana. I am from Brazil. This is my friend Ben. He is from the United States. She is my sister Lia. We are students. They are our teachers. You are in our class too. It is a nice class.

We are happy. I am tall. He is funny. She is smart. They are kind. We are all friends. We like English. You like English too. It is a new language for us. We practice every day. My teacher says, ''You are good students!'' We are proud.

Lia and I are from São Paulo. Ben is from New York. They are far from home. We are in London now. It is a big city. We are here for one year. You can visit us! Are you ready? We are ready.', '[{"answer_index":0,"explanation_pt_br":"No texto, ''He is from the United States'' se refere ao Ben, que é amigo da Ana.","options":["Ben","Ana","Lia","The teacher"],"prompt":"In the text, who is ''he''?"},{"answer_index":0,"explanation_pt_br":"''Lia and I'' (Lia e eu) equivale a ''nós'', então o pronome correto é ''we''.","options":["We","They","You","It"],"prompt":"Which pronoun can replace ''Lia and I''?"},{"answer_index":0,"explanation_pt_br":"A frase fala diretamente com o leitor, então ''you'' significa ''você''.","options":["The reader","Ben","Lia","The teachers"],"prompt":"In ''You are in our class too,'' who is ''you''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-53407bceaca8', 'en', 'A1', 'My Family and I', 'Hello! My name is Ana. I am from Brazil. I have a big family. This is my father. He is a teacher. This is my mother. She is a doctor. They are very busy. We live in a small house. My father is tall. My mother is beautiful. They love us.

My brother is called Pedro. He is twelve years old. He likes soccer. My sister is called Sofia. She is eight. She likes dolls. Our dog is named Rex. It is very friendly. You can visit us on Saturday. We are happy. Pedro and I play video games. We are good friends.', '[{"answer_index":1,"explanation_pt_br":"''They'' se refere ao pai e à mãe de Ana, mencionados anteriormente como ''father'' e ''mother''.","options":["Ana and her brother","Ana''s parents","Ana and her sister","Pedro and Sofia"],"prompt":"In the text, ''They are very busy.'' Who are ''They''?"},{"answer_index":2,"explanation_pt_br":"''It'' se refere ao cachorro Rex, que é apresentado na frase anterior.","options":["The house","The video game","The dog","The school"],"prompt":"In the text, ''It is very friendly.'' What is ''It''?"},{"answer_index":0,"explanation_pt_br":"A frase anterior diz ''Pedro and I play video games.'' Portanto, ''We'' significa Ana e Pedro.","options":["Ana and Pedro","Ana''s parents","Pedro and Sofia","Ana and Sofia"],"prompt":"In the text, ''We are good friends.'' Who are ''We''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-36b5d5e65493', 'en', 'A1', 'Our Day at School', 'Hello! My name is Ana. I am a teacher. I have a small family. This is my husband, Pedro. He is an engineer. We have two children: a son and a daughter. They are students. My son, Lucas, is ten years old. He likes soccer. My daughter, Sofia, is eight. She likes music.

Our dog, Rex, is very funny. It likes to play in the park. You are my new friend. I am happy to meet you. Look at us! We are a happy family. I love my family.

They are in the classroom now. We are ready to learn English. You can see our photos. They are on the wall. We have a nice day today.', '[{"answer_index":0,"explanation_pt_br":"Pedro é o marido da Ana. Como Pedro é homem, usamos o pronome ''He''.","options":["He is my husband.","She is my husband.","It is my husband.","You are my husband."],"prompt":"Who is Pedro?"},{"answer_index":0,"explanation_pt_br":"Lucas e Sofia são duas pessoas (plural). Usamos ''They'' para falar de várias pessoas.","options":["They are students.","He is a student.","She is a student.","We are students."],"prompt":"Who are Lucas and Sofia?"},{"answer_index":0,"explanation_pt_br":"Rex é o cachorro da família. Para animais e objetos, usamos ''It''.","options":["It likes to play in the park.","He likes to play in the park.","She likes to play in the park.","They like to play in the park."],"prompt":"What does Rex like to do?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-8eece813ccfd', 'en', 'A1', 'Meet My Friends', 'Hello! My name is Ana. I am from Brazil. This is my friend John. He is from the United States. He is an engineer. That woman is Maria. She is a teacher. We are students. You are my new classmate. They are doctors. They work at the hospital.

Look at the cat. It is happy. It is on the table. We have a class now. You and I are in the same class. Our teachers are Mr. Smith and Ms. Jones. They are very nice. He is smart. She is busy. Are you ready? Yes, we are! Let''s learn English together.', '[{"answer_index":0,"explanation_pt_br":"No texto, Ana diz: ''I am from Brazil.'' Portanto, Ana é do Brasil.","options":["Ana","John","Maria","The cat"],"prompt":"Who is from Brazil?"},{"answer_index":1,"explanation_pt_br":"Na frase, ''She'' se refere a Maria, pois ela é a mulher mencionada: ''That woman is Maria. She is a teacher.''","options":["Ana","Maria","John","The cat"],"prompt":"In the text, ''She is a teacher.'' Who does ''she'' refer to?"},{"answer_index":1,"explanation_pt_br":"''You and I'' significa ''você e eu'', ou seja, ''nós''. Em inglês, usamos ''we'' para ''nós''.","options":["They","We","He","It"],"prompt":"What pronoun can replace ''You and I'' in the sentence ''You and I are in the same class.''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-3a2d12901c8d', 'en', 'A1', 'My Friends and I', 'Hello! I am Ana. I am from Brazil. This is my friend Pedro. He is a doctor. He works in a hospital. This is Luisa. She is a teacher. She works at a school. They are my friends. We are very happy.

You are my new classmate. Welcome! We have an English class together. It is an easy class. You are a good student. I am a beginner. We are learning English.

My family is big. My father and mother are at home. They are cooks. My brother is young. He is a student. My sister is a nurse. She is kind. I love my family.', '[{"answer_index":0,"explanation_pt_br":"No texto, Pedro é médico. Como falamos de um homem, usamos o pronome ''he'' com o verbo ''is''.","options":["He is a doctor.","She is a teacher.","They are cooks.","It is a hospital."],"prompt":"What does Pedro do?"},{"answer_index":1,"explanation_pt_br":"Luisa é professora. Usamos ''she'' porque é uma mulher, e ''a teacher'' = professora.","options":["She is a nurse.","She is a teacher.","He is a student.","It is a school."],"prompt":"Who is Luisa?"},{"answer_index":0,"explanation_pt_br":"O texto diz que o pai e a mãe de Ana são cozinheiros. Para o plural ''they'', usamos ''are''.","options":["They are cooks.","It is a nurse.","He are doctors.","She are at home."],"prompt":"Which sentence is true about Ana''s family?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-en-a1-7d7ac1cc4fa6', 'en', 'A1', 'Maria and John', 'Maria is a teacher. She lives in São Paulo. She has a dog. It is small and brown. John is her friend. He is an engineer. He works in Rio de Janeiro. They talk on the phone every week. They are good friends.

We are students of English. We study together. You are a student too. You read this lesson. I am happy to learn with you. It is a beautiful day. The sun is bright.

They are Maria''s students. They are from Brazil. They love English. She teaches them new words. He visits her on weekends. We all learn together. This is our class.', '[{"answer_index":0,"explanation_pt_br":"O texto diz: ''Maria is a teacher.'' Portanto, Maria é professora.","options":["A teacher","An engineer","A student","A dog"],"prompt":"Who is Maria?"},{"answer_index":1,"explanation_pt_br":"No texto, Maria é a professora que ensina novas palavras. ''She'' (ela) refere-se a Maria.","options":["John","Maria","The dog","The students"],"prompt":"What does ''She'' refer to in ''She teaches them new words''?"},{"answer_index":0,"explanation_pt_br":"O texto diz que Maria e John falam ao telefone toda semana. ''They'' (eles) refere-se a Maria and John.","options":["Maria and John","The students","You and I","The dog and the sun"],"prompt":"In the sentence ''They talk on the phone every week'', who are ''they''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-2de20dbddc68', 'it', 'A1', 'Un viaggio in Italia', 'Ciao! Oggi parlo del mio viaggio in Italia. Io visito Roma e Milano. Roma è una città bellissima. Ci sono i musei e le piazze. Il Colosseo è un monumento antico. La fontana di Trevi è molto famosa.

Milano è una città moderna. Ci sono i negozi e le università. L''università di Milano è grande. Il mio hotel è vicino alla stazione. Le camere sono pulite e confortevoli.

Mi piace molto la cucina italiana. Ogni giorno mangio la pizza o la pasta. Gli italiani sono molto gentili. I ristoranti sono ottimi. Nel mio viaggio, io uso la macchina fotografica. Le foto sono belle. Alla fine, io compro alcuni regali per la mia famiglia. I regali sono piccoli e carini. Questo viaggio è indimenticabile!', '[{"answer_index":0,"explanation_pt_br":"O Coliseu é um monumento antigo, como diz o texto.","options":["Un monumento","Una città","Un negozio","Un ristorante"],"prompt":"Che cosa è il Colosseo?"},{"answer_index":0,"explanation_pt_br":"A palavra ''piazza'' é feminina singular; o plural é ''piazze'' com o artigo feminino plural ''le''.","options":["la piazza","il piazza","la piazzo","il piazzo"],"prompt":"Nel testo, ''le piazze'' è il plurale di quale parola?"},{"answer_index":1,"explanation_pt_br":"A palavra ''museo'' é masculina, pois usamos o artigo ''il''. As outras são femininas.","options":["città","museo","fontana","camere"],"prompt":"Quale di queste parole è maschile?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-9e0205d59ed0', 'it', 'A1', 'La mia università', 'Salve! Mi chiamo Marco. Abito a Milano. Studio all''università. Ogni giorno vado a piedi. L''università è grande e moderna. Ci sono molti studenti. I professori sono bravi. La biblioteca è silenziosa. I libri sono interessanti. Le lezioni cominciano alle nove.

Nella mia classe ci sono dieci studenti. Loro sono di paesi diversi. La mia compagna è brasiliana. Il mio compagno è francese. Noi parliamo italiano. Le professoresse sono gentili. Oggi abbiamo un esame. L''esame è facile.

Dopo le lezioni, mangiamo nella mensa. La pizza è buona. I panini sono buoni. Le bevande sono fredde. L''acqua è importante. Io studio sempre. L''italiano è una lingua bella.', '[{"answer_index":1,"explanation_pt_br":"O texto diz: \"Abito a Milano.\" Portanto, Marcos mora em Milão.","options":["A Roma","A Milano","A Firenze","A Napoli"],"prompt":"Dove abita Marco?"},{"answer_index":1,"explanation_pt_br":"O texto diz: \"Nella mia classe ci sono dieci studenti.\" Portanto, há dez estudantes.","options":["cinque","dieci","venti","dodici"],"prompt":"Quanti studenti ci sono nella classe di Marco?"},{"answer_index":2,"explanation_pt_br":"No texto: \"I panini sono buoni.\" Panini é masculino plural, então o adjetivo concorda: buoni.","options":["buona","buone","buoni","buono"],"prompt":"Completa la frase: \"I panini sono ______.\""}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-79014da668de', 'it', 'A1', 'La mia università', 'Guardo una foto della mia università. L''università è grande e bella. Ci sono molti studenti. I professori sono gentili. Le aule sono moderne. C''è una biblioteca con molti libri. Il libro di italiano è sul tavolo. La biblioteca è aperta tutti i giorni.

Gli studenti studiano insieme. Le professoresse parlano con gli studenti. L''università ha un giardino e un bar. I giardini sono verdi. I bar sono piccoli ma buoni. Oggi ho una lezione di italiano. La lezione è interessante. Io imparo le parole nuove. Le parole sono facili. Gli articoli sono importanti.

Questo è un esercizio facile. Questa è una frase semplice.', '[{"answer_index":1,"explanation_pt_br":"''Professori'' é o plural masculino de ''professore''. O artigo definido masculino plural é ''i''.","options":["Perché ''professori'' è maschile singolare.","Perché ''professori'' è maschile plurale.","Perché ''professori'' è femminile plurale.","Perché ''professori'' è femminile singolare."],"prompt":"Nella frase ''I professori sono gentili'', perché usiamo ''i''?"},{"answer_index":3,"explanation_pt_br":"''Aule'' é um substantivo feminino plural, então o artigo definido é ''le''.","options":["il","lo","la","le"],"prompt":"Qual è l''articolo corretto per ''aule''?"},{"answer_index":0,"explanation_pt_br":"''Biblioteca'' é um substantivo feminino singular, por isso usamos o artigo indefinido ''una''.","options":["Perché ''biblioteca'' è femminile singolare.","Perché ''biblioteca'' è maschile singolare.","Perché ''biblioteca'' è femminile plurale.","Perché ''biblioteca'' è maschile plurale."],"prompt":"Nella frase ''C''è una biblioteca'' perché usiamo ''una''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-079280c95d7a', 'it', 'A1', 'La mia università', 'Ciao! Mi chiamo Marco e studio all''università di Firenze. La mia università è antica e molto bella. Il palazzo ha una grande porta. Gli studenti vengono da ogni parte del mondo. Le classi sono piccole ma comode. Io ho un professore di italiano simpatico. La professoressa di matematica è severa. I libri sono nuovi. Le lezioni cominciano alle nove.

Oggi è il primo giorno. Io incontro una ragazza e un ragazzo. Loro sono brasiliani. I brasiliani sono gentili. Noi parliamo in italiano. La lingua è difficile, ma gli amici aiutano. C''è una biblioteca con molti libri. Il ristorante universitario offre un pasto buono e economico. Le aule sono vicino al giardino. Io sono contento di studiare qui.', '[{"answer_index":1,"explanation_pt_br":"No texto, encontramos ''una ragazza'' e ''una biblioteca''. ''Una'' é o artigo indefinido feminino singular.","options":["un","una","uno","il"],"prompt":"Qual è l''articolo indeterminativo femminile singolare presente nel testo?"},{"answer_index":2,"explanation_pt_br":"No texto, aparece ''gli studenti''. Em italiano, ''gli'' é o artigo definido masculino plural usado antes de vogal e de ''s+consoante'' (st, sp, etc.).","options":["il","i","gli","le"],"prompt":"Qual è l''articolo determinativo maschile plurale usato con ''studenti'' nel testo?"},{"answer_index":2,"explanation_pt_br":"No texto, ''le classi sono piccole''. O artigo definido feminino plural é ''le''.","options":["il","la","le","i"],"prompt":"Qual è l''articolo determinativo femminile plurale per ''classi'' nel testo?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-c48f75d72fbe', 'it', 'A1', 'La classifica delle università', 'Nel 2008, il quotidiano Il Sole 24 Ore ha pubblicato una classifica delle università italiane. La classifica è una lista. Questa lista mostra le università migliori. Al primo posto c''è il Politecnico di Milano. Ha 721 punti. L''ultima università è a Napoli. Si chiama Parthenope e ha solo 164 punti.

Le università statali sono molte. Alcune sono grandi, altre sono piccole. Ci sono università antiche e università nuove. Gli studenti possono scegliere un corso di studi. La ricerca e la didattica sono cose importanti per una buona università. La classifica aiuta gli studenti a capire le differenze tra le università.

Ma la classifica non dice tutto. Ogni studente deve visitare le università. Deve parlare con i professori e vedere le aule. Così può scegliere bene.', '[{"answer_index":0,"explanation_pt_br":"O texto afirma: ''La classifica è una lista.'' Portanto, a resposta correta é ''una lista''.","options":["Una lista","Un libro","Una casa","Un lavoro"],"prompt":"Secondo il testo, che cosa è la classifica?"},{"answer_index":1,"explanation_pt_br":"''Università'' é um substantivo feminino invariável no plural. O artigo definido feminino plural é ''le''. Portanto, ''Le università sono molte'' é a forma correta.","options":["Il università sono molte.","Le università sono molte.","La università sono molte.","Gli università sono molte."],"prompt":"Quale frase usa l''articolo corretto per ''università''?"},{"answer_index":0,"explanation_pt_br":"''Classifica'' é um substantivo feminino singular, então o artigo indefinido é ''una''.","options":["una","un","uno","il"],"prompt":"Completa la frase: ''Il Sole 24 Ore ha pubblicato ___ classifica.''"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-ea5aa8c80600', 'it', 'A1', 'Una giornata all''università', 'Oggi è il primo giorno di università. La studentessa Maria arriva all''aula. Il professore Rossi parla con gli studenti. I libri nuovi sono sul banco. Le lezioni iniziano alle nove. La classe è grande e luminosa.

Nella biblioteca, gli amici di Maria studiano. L''esame di italiano è difficile, ma i ragazzi sono contenti. Le ragazze leggono i libri di storia. Il tempo passa veloce. La biblioteca è silenziosa, ma le persone sono gentili.

Alla fine, Maria e gli amici vanno al bar. La pizza è buona. I caffè sono piccoli e forti. Le amiche di Maria sono simpatiche. I professori sono stanchi. Le aule sono vuote. Che bella giornata!', '[{"answer_index":1,"explanation_pt_br":"O texto diz: ''La studentessa Maria arriva all''aula.'' Portanto, a pessoa que chega à sala de aula é a estudante Maria.","options":["Il professore Rossi","La studentessa Maria","Gli amici","Le ragazze"],"prompt":"Chi arriva all''aula?"},{"answer_index":2,"explanation_pt_br":"O texto afirma: ''I libri nuovi sono sul banco.'' Assim, os livros novos estão sobre a mesa.","options":["I caffè","Le pizze","I libri nuovi","Gli esami"],"prompt":"Cosa c''è sul banco?"},{"answer_index":3,"explanation_pt_br":"O texto diz: ''Le amiche di Maria sono simpatiche.'' Portanto, elas são simpáticas.","options":["Stanche","Grandi","Difficili","Simpatiche"],"prompt":"Come sono le amiche di Maria?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-752710dbf396', 'it', 'A1', 'Le università italiane', 'Le università italiane sono molto antiche. L''Università di Bologna è la più antica d''Europa. Il Politecnico di Milano è una grande università tecnica. La Sapienza di Roma è una università pubblica importante. Queste università sono famose.

Un professore insegna matematica. Una professoressa insegna storia. Lo studente studia ogni giorno. Gli studenti leggono i libri e scrivono le risposte. Le lezioni sono interessanti. Le biblioteche sono piene di libri.

Alcune università sono private, ma molte sono pubbliche. I professori sono esperti nelle loro materie. Gli studenti fanno gli esami. Una studentessa studia medicina. Un altro studente studia ingegneria. Le università offrono molti corsi.', '[{"answer_index":1,"explanation_pt_br":"No texto, a palavra ''studenti'' (estudantes) é masculina plural e começa com ''st'' (s + consoante), portanto o artigo correto é ''gli''.","options":["i","gli","le","il"],"prompt":"Quale articolo determinativo si usa con il nome ''studenti'' nel testo?"},{"answer_index":2,"explanation_pt_br":"''Università'' é uma palavra feminina singular, mesmo terminando em ''à''. As outras opções são masculinas ou plurais.","options":["studente","professore","università","libro"],"prompt":"Quale parola è femminile singolare?"},{"answer_index":2,"explanation_pt_br":"''Professoressa'' é feminina singular, portanto usa-se o artigo indeterminativo ''una''.","options":["un","uno","una","il"],"prompt":"Che articolo indeterminativo si usa con ''professoressa''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-ebc2ecbac905', 'it', 'A1', 'Una giornata all''università', 'Marco è uno studente di medicina. Ogni giorno va all''università in autobus. Oggi ha lezione di inglese e di biologia. L''aula è grande e luminosa. I suoi libri sono nella borsa, insieme alle penne. Tutti gli studenti aspettano la professoressa. L''aula ha molte finestre e una lavagna bianca.

La professoressa arriva con un caffè. La lezione è interessante, ma è difficile. Gli studenti scrivono molto. Marco guarda l''orologio. Il tempo passa. Dopo la lezione, parla con una compagna. Lei ha un libro nuovo. Loro escono insieme e vanno al bar. Al bar, prendono un succo e parlano delle lezioni. Sono contenti perché la giornata è bella.', '[{"answer_index":1,"explanation_pt_br":"O plural de ''libro'' (masculino singular) é ''i libri'', pois substantivos masculinos terminados em -o formam o plural com -i.","options":["il libro","i libri","la libra","le libri"],"prompt":"Qual è il plurale di ''libro''?"},{"answer_index":1,"explanation_pt_br":"''Compagna'' é um substantivo feminino singular, e o artigo indefinido ''una'' confirma o gênero feminino.","options":["maschile singolare","femminile singolare","maschile plurale","femminile plurale"],"prompt":"Nel testo, ''una compagna'' è:"},{"answer_index":2,"explanation_pt_br":"Como ''studenti'' é masculino plural e começa com s+consoante, usamos o artigo definido ''gli''.","options":["il","la","gli","le"],"prompt":"Quale articolo è corretto con ''studenti''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-4477ec8f5970', 'it', 'A1', 'Le università italiane', 'Le università italiane sono molte. Ogni anno, il quotidiano Il Sole 24 Ore pubblica una classifica. La classifica parla di ricerca e didattica. Nel 2008, la prima università è il Politecnico di Milano. Ha 721 punti. L''ultima università è a Napoli. Ha 164 punti.

Le prime cinque università sono il Politecnico di Milano, l''Università di Trieste, l''Università di Modena, l''Università di Pavia e l''Università di Trento. Le università grandi sono importanti per la ricerca. I professori lavorano con gli studenti. Le città universitarie sono belle.

In Italia, gli studenti studiano molte materie. Le materie sono diverse. La matematica è difficile, ma la storia è interessante. I libri sono cari. Le biblioteche sono utili. Gli studenti amano le università.', '[{"answer_index":0,"explanation_pt_br":"O texto diz: \"la prima università è il Politecnico di Milano\".","options":["Politecnico di Milano","Università di Trieste","Università di Pavia","Università di Trento"],"prompt":"Secondo il testo, qual è la prima università nella classifica?"},{"answer_index":0,"explanation_pt_br":"Usamos \"gli\" antes de palavras masculinas plurais que começam com s + consoante, como \"studenti\".","options":["gli","i","le","il"],"prompt":"Qual è l''articolo determinativo plurale maschile per la parola \"studenti\"?"},{"answer_index":0,"explanation_pt_br":"O singular de \"materie\" é \"materia\". Em italiano, muitas palavras femininas terminam em -a no singular e -e no plural.","options":["materia","materie","materio","materi"],"prompt":"Nel testo, la parola \"materie\" è femminile plurale. Qual è il singolare?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-c215748cbc5e', 'it', 'A1', 'Le università italiane', 'Oggi visitiamo un''università italiana. Questa è l''Università di Bologna, una delle più antiche del mondo. Il portone è grande e vecchio. La biblioteca è moderna. Nella biblioteca ci sono molti libri. I libri sono interessanti. Le riviste sono nuove. I professori sono gentili. Le professoresse sono preparate. Gli studenti frequentano le lezioni. Le studentesse studiano nella biblioteca.

Nella classe ci sono un tavolo, una sedia, un libro e una penna. I quaderni sono aperti. Le borse sono sotto il tavolo. L''orario delle lezioni è sul sito. Il professore spiega la lezione. La professoressa ascolta gli studenti. I corsi sono interessanti. Le università italiane sono antiche e famose. Gli studenti amano l''università. Le studentesse amano la cultura.', '[{"answer_index":1,"explanation_pt_br":"A palavra ''università'' é feminina singular, então o artigo correto é ''la''.","options":["Il","La","Le","I"],"prompt":"Completa la frase: ______ università è grande."},{"answer_index":2,"explanation_pt_br":"No plural masculino, ''professore'' vira ''professori''. O artigo ''i'' exige o plural masculino.","options":["professore","professoresse","professori","professor"],"prompt":"Completa la frase: I ______ sono gentili."},{"answer_index":0,"explanation_pt_br":"''Studentesse'' é plural feminino, então o artigo é ''le''.","options":["Le","La","Gli","I"],"prompt":"Completa la frase: ______ studentesse studiano."}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-593fa6ba250f', 'it', 'A1', 'La mia università', 'Questa è la mia università. Il campus è grande e moderno. Ci sono molti edifici. Le aule sono luminose. I professori sono gentili. Gli studenti sono attenti. La biblioteca è tranquilla. La mensa è buona. Le studentesse sono simpatiche.

Nel campus ci sono anche i giardini. I fiori sono colorati. Gli alberi sono alti. Le panchine sono comode. Gli amici si incontrano al bar. Il caffè è buono. La pizza è gustosa. Anche i dolci sono buoni.

La mia classe è piccola. Le finestre sono grandi. I computer sono nuovi. Gli esercizi sono facili. La lezione di italiano è interessante. I libri sono sul tavolo. I quaderni sono bianchi. La lezione comincia alle nove.', '[{"answer_index":2,"explanation_pt_br":"''Professori'' é um substantivo masculino no plural. O artigo definido masculino plural é ''i'' (os). Exemplo no texto: ''I professori sono gentili.'' Em português: ''Os professores são gentis.''","options":["Il","La","I","Le"],"prompt":"Completa la frase: ''____ professori sono gentili.''"},{"answer_index":0,"explanation_pt_br":"''Studentessa'' é feminino. O plural de ''la'' é ''le'' para palavras femininas. Portanto, ''le studentesse'' (as estudantes). No texto: ''Le studentesse sono simpatiche.''","options":["Le studentesse","La studentesse","I studentesse","Gli studentesse"],"prompt":"Qual è il plurale di ''la studentessa''?"},{"answer_index":2,"explanation_pt_br":"''Giardini'' é masculino plural. Usamos ''i'' para masculino plural que começa com consoante (não ''s+consoante'', ''z'', etc.). Em português: ''Os jardins são coloridos.''","options":["La","Le","I","Gli"],"prompt":"Completa la frase: ''____ giardini sono colorati.''"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-26919487c72f', 'it', 'A1', 'La mia casa', 'Mi chiamo Mario. Vivo in una casa grande con la mia famiglia. La casa ha tre camere da letto, due bagni, un giardino e una cucina moderna. I miei genitori sono italiani, ma mio padre è avvocato e mia madre è insegnante.

La mia camera è piccola ma carina. C''è un letto, una scrivania, una libreria e un armadio. Le pareti sono bianche e il pavimento è in legno. I miei amici vengono spesso a trovarmi. A volte guardiamo un film o ascoltiamo la musica.

Nella casa ci sono molte piante. Le piante sono verdi e belle. Dal balcone vedo un parco con alberi e fiori. Mi piace molto la mia casa.', '[{"answer_index":1,"explanation_pt_br":"Casa é um substantivo feminino singular, por isso usamos o artigo ''la''.","options":["il","la","i","le"],"prompt":"Qual è l''articolo determinativo corretto per ''casa''?"},{"answer_index":0,"explanation_pt_br":"Substantivos femininos terminados em -a formam o plural em -e, e o artigo ''la'' vira ''le''.","options":["le camere","i camere","la camere","le camera"],"prompt":"Qual è il plurale di ''la camera''?"},{"answer_index":0,"explanation_pt_br":"Substantivos masculinos terminados em -o formam o plural em -i, e o artigo ''il'' vira ''i''.","options":["i pavimenti","le pavimenti","il pavimenti","i pavimento"],"prompt":"Qual è il plurale di ''il pavimento''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-2081004c6b47', 'it', 'A1', 'La mia aula', 'Questa è la mia aula. C''è un tavolo grande e una sedia bianca. Il professore è italiano e la professoressa è brasiliana. Gli studenti sono giovani e le studentesse sono simpatiche. Io ho un libro e una penna. Il libro è nuovo, la penna è blu. Ci sono anche due finestre e tre porte. Le finestre sono aperte, le porte sono chiuse. L''aula è bella e luminosa.

Sul tavolo ci sono un computer e una borsa. Il computer è grigio e la borsa è rossa. Gli amici di Marco hanno un quaderno e una matita. Il quaderno è grande, la matita è piccola. Le sedie sono marroni e i banchi sono verdi. Tutti gli oggetti sono in ordine.

Oggi noi leggiamo una lezione interessante. La lezione parla degli articoli in italiano. Gli articoli sono importanti per parlare bene. Le professoresse spiegano la differenza tra "il" e "gli", e tra "la" e "le". Noi ascoltiamo con attenzione. La scuola è un posto fantastico per imparare.', '[{"answer_index":1,"explanation_pt_br":"Usamos \"il\" porque \"professore\" é um substantivo masculino singular. Em português, \"professor\" é masculino.","options":["la","il","le","gli"],"prompt":"Nella frase \"Il professore è italiano\", che articolo usiamo con \"professore\"?"},{"answer_index":0,"explanation_pt_br":"\"Penna\" é um substantivo feminino singular. O plural de substantivos femininos com artigo definido é \"le\". Portanto, \"le penne\".","options":["le penne","la penne","le penna","li penne"],"prompt":"Qual è il plurale di \"la penna\"?"},{"answer_index":2,"explanation_pt_br":"\"Studenti\" é masculino plural. Antes de \"s + consoante\" usamos \"gli\" no plural masculino. Por isso, \"gli studenti\".","options":["il","la","gli","le"],"prompt":"Che articolo usiamo con \"studenti\" (plurale maschile)?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-a611641049cc', 'it', 'A1', 'Le università italiane', 'Questa è una classifica delle università italiane. Il giornale Sole 24 Ore è un giornale economico importante. Ogni anno pubblica una lista delle migliori università. Il Politecnico di Milano è al primo posto con 721 punti. L''Università di Trieste è al secondo posto con 713 punti. La classifica usa molti criteri.

Nelle università lavorano i professori e gli studenti. I professori insegnano e gli studenti studiano. Ogni corso ha un programma. Una università ha anche una biblioteca. Le biblioteche sono spazi importanti per lo studio.

Le università statali sono pubbliche. Gli studenti scelgono una università in base alla classifica. L''ultima università nella classifica ha solo 164 punti. Le università in cima hanno molti punti. Un''università è un''opportunità di formazione per tutti.', '[{"answer_index":1,"explanation_pt_br":"O artigo feminino singular é ''la''. Exemplo no texto: ''la classifica''.","options":["il","la","le","i"],"prompt":"Qual è l''articolo determinativo femminile singolare?"},{"answer_index":2,"explanation_pt_br":"''Studenti'' é masculino plural, portanto o artigo correto é ''gli'' (usado antes de vogal ou s+consoante). No texto vemos ''gli studenti''.","options":["Il","La","Gli","Le"],"prompt":"Completa la frase: ______ studenti studiano."},{"answer_index":1,"explanation_pt_br":"''Professore'' é masculino singular; o plural é ''i professori'', como no texto.","options":["il professori","i professori","le professori","la professori"],"prompt":"Qual è il plurale di ''il professore''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-f694ea478717', 'it', 'A1', 'La scuola di Marco', 'La scuola di Marco è grande e bella. La classe è nuova. Il professore di italiano è simpatico. La professoressa di storia è intelligente. Gli studenti sono bravi e le studentesse sono gentili. Il preside è alto. La segretaria è socievole. Anche la mensa è spaziosa. Le aule sono luminose.

Nella classe ci sono molti oggetti. Un libro è sul banco. Una penna è nella borsa. Un quaderno è nello zaino. I libri sono rossi. Le penne sono verdi. I quaderni sono blu. La porta è marrone. Le finestre sono bianche. Il banco è piccolo. Le sedie sono nere. La lavagna è grande. I muri sono gialli.', '[{"answer_index":0,"explanation_pt_br":"Em italiano, o feminino de ''professore'' é ''professoressa''. A forma ''professora'' não existe em italiano.","options":["professoressa","professora","professor","professore"],"prompt":"Qual è il femminile di ''professore''?"},{"answer_index":0,"explanation_pt_br":"''Libro'' é um substantivo masculino singular. O plural é ''libri''.","options":["libri","libra","libre","libro"],"prompt":"Qual è il plurale di ''libro''?"},{"answer_index":1,"explanation_pt_br":"''Studenti'' começa com ''st'' (s + consoante), por isso usa-se o artigo ''gli'' no plural.","options":["i","gli","le","la"],"prompt":"Quale articolo si usa con ''studenti''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-c045f5ba9658', 'it', 'A1', 'La famiglia Rossi', 'La famiglia Rossi è numerosa. Il padre si chiama Paolo e la madre si chiama Anna. Hanno tre figli: un maschio e due femmine. Il figlio, Luca, ha dieci anni. Le figlie, Giulia e Sara, hanno otto e sei anni. La famiglia abita in una grande casa con un giardino.

Nel giardino ci sono molti alberi e fiori colorati. C''è anche un cane, un gatto e due conigli. Il cane è nero e molto grande. Il gatto è bianco e piccolo. I conigli sono marroni e veloci. La casa ha cinque stanze: la cucina, il salotto, la camera dei genitori e due camere per i figli.

Le camere dei figli sono belle e ordinate. Nella camera di Luca ci sono i giocattoli e le macchine. Nella camera delle bambine ci sono le bambole e i libri. La famiglia Rossi è felice nella sua casa.', '[{"answer_index":1,"explanation_pt_br":"O texto diz: ''Hanno tre figli: un maschio e due femmine.'' Portanto, há duas filhas.","options":["Una","Due","Tre","Quattro"],"prompt":"Quantas filhas mulheres há na família Rossi?"},{"answer_index":1,"explanation_pt_br":"Em italiano, ''figlie'' é feminino plural, então o artigo correto é ''le''.","options":["La","Le","Il","I"],"prompt":"Complete a frase: ''___ figlie sono Giulia e Sara.''"},{"answer_index":0,"explanation_pt_br":"O texto diz: ''C''è anche un cane, un gatto e due conigli.''","options":["Un cane, un gatto e due conigli","Un cavallo e tre uccelli","Un pesce e un topo","Solo fiori"],"prompt":"O que há no jardim?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-it-a1-21ce79d7bcb3', 'it', 'A1', 'Le università italiane', 'Le università italiane sono molte e diverse. Ogni città ha una storia e una cultura differente. Il Politecnico di Milano è una università tecnica molto prestigiosa. L''Università di Bologna è una delle più antiche del mondo. Gli studenti italiani frequentano le lezioni e studiano nelle biblioteche. Le biblioteche moderne offrono molti libri, computer e spazi tranquilli. I professori sono preparati e gentili. Essi aiutano gli studenti a capire temi difficili.

Ogni anno, nuovi studenti scelgono un corso di laurea. Alcuni corsi sono scientifici, altri sono umanistici. Per alcune facoltà, come Medicina, gli studenti devono passare un esame di ammissione. Questo esame è molto difficile e selettivo. Chi lo supera può iniziare le lezioni. Gli altri devono aspettare l''anno successivo o scegliere un''altra università.

La vita universitaria è un''esperienza importante per il futuro. Gli studenti imparano non solo materie, ma anche autonomia e responsabilità. Inoltre, possono partecipare a progetti di ricerca e a scambi internazionali. Le università offrono anche servizi come mense, borse di studio e alloggi. Per molti giovani, l''università è il primo passo verso una carriera professionale.', '[{"answer_index":0,"explanation_pt_br":"No texto, ''biblioteche'' é um substantivo feminino plural, como indica o artigo ''le'' que o acompanha.","options":["femminile plurale","maschile plurale","femminile singolare","maschile singolare"],"prompt":"Nel testo, ''biblioteche'' è un sostantivo:"},{"answer_index":0,"explanation_pt_br":"O plural de ''studente'' (masculino) é ''studenti''. ''Studentesse'' é o plural de ''studentessa'' (feminino).","options":["studenti","studenta","studentesse","studente"],"prompt":"Qual è il plurale maschile di ''studente''?"},{"answer_index":0,"explanation_pt_br":"Com substantivos masculinos plurais começados por consoante, usamos ''i''. ''Gli'' é usado antes de vogal ou ''s''+consoante.","options":["i","gli","le","il"],"prompt":"Quale articolo determinativo si usa con ''professori''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();
