-- GENERATED FILE: review source provenance and content before applying.
-- Content is unpublished unless --publish was explicitly used.

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-7ea2d3b08ff3', 'es', 'A1', 'Un acuerdo entre Brasil y España', 'El ministro de educación de Brasil y el embajador de España firmaron un acuerdo muy importante. El acuerdo incluye programas de intercambio y formación. Los dos países quieren ayudar a los profesores y a los estudiantes. La cooperación es una oportunidad para las escuelas.

Unos estudiantes brasileños van a España para estudiar. Unas profesoras españolas vienen a Brasil para enseñar. Las universidades participan en el programa. Las clases son en portugués y en español, pero las lenguas son similares. Los profesores aprenden cosas nuevas.

El portugués y el español son lenguas cercanas. La comunicación es fácil. Los acuerdos como este son excelentes para las personas. La educación es una herramienta útil. Los intercambios son importantes para el futuro.', '[{"answer_index":0,"explanation_pt_br":"O texto diz que eles assinaram ''un acuerdo muy importante''. ''Acuerdo'' é masculino singular, por isso usamos ''un''.","options":["un acuerdo","una escuela","los libros","las clases"],"prompt":"¿Qué firmaron el ministro y el embajador?"},{"answer_index":0,"explanation_pt_br":"Em espanhol, ''acuerdo'' é masculino e no plural se diz ''los acuerdos''. O adjetivo ''buenos'' concorda em gênero e número.","options":["Los acuerdos son buenos.","La acuerdos son buenos.","Las acuerdo son buenos.","El acuerdos son buenos."],"prompt":"¿Cuál frase es correcta según el texto?"},{"answer_index":0,"explanation_pt_br":"O texto diz ''Las universidades...''. ''Universidades'' é feminino e plural, por isso usamos ''las''.","options":["las","la","el","los"],"prompt":"En el texto, ¿qué artículo usamos con ''universidades''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-2dccc8f309b9', 'es', 'A1', 'Un acuerdo de educación', 'Brasil y España firman un acuerdo de educación. Los dos países quieren ayudar a los profesores y a los estudiantes. La ministra de Brasil y el embajador de España firman el memorando. Los proyectos reciben el apoyo de una organización internacional.

Los estudiantes brasileños pueden estudiar en las universidades españolas. Las universidades ofrecen cursos para los brasileños. Un profesor dice: ''El idioma no es una barrera.'' Los brasileños y los españoles comparten la lengua portuguesa y la lengua española. Unos programas son para la investigación. Las ideas del acuerdo son buenas para la educación.

También hay una noticia de Asturias. Las personas salen a las calles por la lengua asturiana. La lengua es importante para la cultura. Unos manifestantes llevan pancartas. Los políticos escuchan las peticiones. La lengua es parte de la vida.', '[{"answer_index":1,"explanation_pt_br":"''Ministra'' é um substantivo feminino singular, por isso o artigo definido correto é ''la''. Em espanhol, usamos ''la'' para feminino singular.","options":["El","La","Los","Las"],"prompt":"Completa la frase con el artículo correcto: ''___ ministra de Brasil firma el acuerdo.''"},{"answer_index":3,"explanation_pt_br":"''Universidades'' é plural feminino. O artigo definido feminino plural é ''las''. Cuidado: ''los'' é masculino plural.","options":["el","la","los","las"],"prompt":"Completa la frase: ''Los estudiantes estudian en ___ universidades españolas.''"},{"answer_index":0,"explanation_pt_br":"''Profesor'' é masculino singular. O artigo indefinido masculino singular é ''un''. ''Una'' seria para feminino.","options":["un","una","unos","las"],"prompt":"¿Cuál es el artículo indefinido correcto para ''profesor''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-2524379251ca', 'es', 'A1', 'Mi casa', 'Mi casa está en el centro de la ciudad. Es una casa pequeña pero tiene dos plantas. En la planta baja hay una cocina, un comedor y un baño. La cocina es blanca y tiene una nevera. El comedor es amplio con una mesa grande. El baño es pequeño pero moderno.

En la planta alta hay dos dormitorios y un salón. El dormitorio de mis padres es grande. Las camas son cómodas. El otro dormitorio es el mío. Mi dormitorio tiene una ventana grande. El salón tiene un sofá, unos cuadros y una televisión. Las paredes son amarillas.

Me gusta mi casa porque es tranquila. Los vecinos son amables. La calle es silenciosa. En el jardín hay flores y árboles.', '[{"answer_index":1,"explanation_pt_br":"O texto diz: ''hay dos dormitorios''.","options":["Uno","Dos","Tres","Cuatro"],"prompt":"¿Cuántos dormitorios hay en la casa?"},{"answer_index":0,"explanation_pt_br":"A cozinha é branca, como diz o texto.","options":["Blanca","Amarilla","Azul","Verde"],"prompt":"¿De qué color es la cocina?"},{"answer_index":2,"explanation_pt_br":"A casa fica no centro da cidade, conforme a primeira frase.","options":["En el campo","En la playa","En el centro de la ciudad","En las montañas"],"prompt":"¿Dónde está la casa?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-458be1a6dc36', 'es', 'A1', 'Un acuerdo de educación', 'Brasil y España firman un acuerdo de colaboración. El ministro de Educación de Brasil y el embajador de España están presentes. El acuerdo es para la formación de profesores y para los estudiantes. Los programas de intercambio son importantes. La educación es un tema central.

Los proyectos reciben apoyo de una organización. Un profesor brasileño puede viajar a España. Una estudiante española puede estudiar en Brasil. Las universidades tienen mucho conocimiento. Los idiomas no son una barrera. El portugués y el español son lenguas cercanas.

Muchos brasileños viven en España. Muchas españolas viven en Brasil. Los estudiantes comparten experiencias. Las clases de idiomas son útiles. Un profesor nuevo llega a la escuela. Una profesora prepara las actividades.', '[{"answer_index":0,"explanation_pt_br":"''Acuerdo'' é uma palavra masculina e singular. Por isso, usamos o artigo ''el''.","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo correcto para la palabra ''acuerdo''?"},{"answer_index":2,"explanation_pt_br":"''Estudiantes'' é um substantivo plural e, nesse contexto, usamos ''los'' porque é masculino ou misto. Em espanhol, o artigo masculino plural também é usado para grupos mistos.","options":["El","La","Los","Las"],"prompt":"Completa la frase: ''____ estudiantes comparten experiencias.''"},{"answer_index":3,"explanation_pt_br":"''Universidades'' é um substantivo feminino e plural, por isso usamos o artigo ''las''.","options":["El","La","Los","Las"],"prompt":"Completa la frase: ''____ universidades tienen mucho conocimiento.''"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-255310962fd0', 'es', 'A1', 'Un acuerdo entre dos países', 'Brasil y España firman un acuerdo de educación. El ministro de Educación de Brasil y el embajador de España están en una oficina. Ellos hablan de los estudiantes y los profesores. Las universidades de los dos países participan en el proyecto. El acuerdo es bueno para la educación y la ciencia. Los investigadores pueden trabajar juntos.

Muchas personas viven en España y en Brasil. Los brasileños aprenden español. Las escuelas tienen clases de idiomas. Un profesor dice: ''El español y el portugués son lenguas hermanas''. Los estudiantes están felices con la oportunidad. Ellos quieren viajar a España. Las familias también apoyan la idea. El acuerdo es una buena noticia para todos.', '[{"answer_index":0,"explanation_pt_br":"Em espanhol, ''acuerdo'' é um substantivo masculino singular, por isso usamos o artigo definido ''el''.","options":["el","la","los","las"],"prompt":"En el texto, la palabra ''acuerdo'' tiene el artículo:"},{"answer_index":1,"explanation_pt_br":"''Oficina'' é um substantivo feminino singular, então o artigo indefinido correto é ''una''.","options":["un","una","unos","unas"],"prompt":"En el texto, ¿qué artículo usamos con ''oficina''?"},{"answer_index":0,"explanation_pt_br":"O plural de ''el estudiante'' é ''los estudiantes'', pois no plural usamos ''los'' para substantivos masculinos.","options":["los estudiantes","las estudiantes","el estudiantes","la estudiantes"],"prompt":"En el texto, ¿cuál es el plural de ''el estudiante''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-5ae50be7ecbc', 'es', 'A1', 'La clase de español', 'Esta es la clase de español. Hay una profesora y dos profesores. La profesora se llama Ana. Los estudiantes son de Brasil y de España. En la mesa hay unos libros y unas mochilas. El libro azul es de Pedro. La mochila roja es de María. También hay un cuaderno verde y una pluma negra.

Hoy los estudiantes hablan español. Un estudiante lee un texto. Las ventanas están abiertas. Los relojes están en la pared. La profesora escribe en la pizarra. Los estudiantes escuchan con atención. Unos estudiantes levantan la mano.

Después de la clase, los estudiantes van a casa. Tienen unas tareas fáciles y un examen difícil. La tarea de español es para mañana. El examen es el viernes. Los estudiantes están contentos porque les gusta la clase.', '[{"answer_index":1,"explanation_pt_br":"Porque ''profesora'' é um substantivo feminino e singular, por isso usamos o artigo ''la''.","options":["el","la","los","las"],"prompt":"En el texto, la palabra ''profesora'' usa el artículo..."},{"answer_index":1,"explanation_pt_br":"Porque ''libros'' é masculino plural e ''mochilas'' é feminino plural. Usamos ''unos'' e ''unas'' para plurais indeterminados.","options":["un / una","unos / unas","los / las","el / la"],"prompt":"Completa la frase del texto: ''En la mesa hay ______ libros y ______ mochilas.''"},{"answer_index":2,"explanation_pt_br":"Porque ''estudiantes'' é plural e pode ser masculino ou misto. No texto usamos ''los estudiantes'' para nos referir ao grupo em geral.","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo definido correcto para ''estudiantes'' en español?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-82ab77c37eca', 'es', 'A1', 'Un acuerdo para la educación', 'Brasil y España tienen un nuevo acuerdo. Los dos países quieren aprender juntos. El gobierno de Brasil y el gobierno de España firman un plan para la educación. Este plan incluye viajes para estudiantes y profesores.

Los estudiantes pueden vivir en el otro país. Las universidades abren las puertas para los brasileños y los españoles. Hay muchas ideas nuevas en las escuelas. La educación es muy importante para las personas.

Unos cien mil brasileños viven en España. Y unos ciento cincuenta mil españoles viven en Brasil. Las lenguas son parecidas. El portugués y el español tienen palabras iguales. Las personas pueden hablar sin mucho problema. El acuerdo es bueno para el futuro.', '[{"answer_index":0,"explanation_pt_br":"Usamos ''un'' porque ''acuerdo'' é um substantivo masculino e singular. ''Una'' é para feminino, ''unos'' e ''unas'' são para plural.","options":["un","una","unos","unas"],"prompt":"Completa la frase: ''Brasil y España tienen ___ nuevo acuerdo.''"},{"answer_index":3,"explanation_pt_br":"Usamos ''Las'' porque ''universidades'' é um substantivo feminino e plural. ''El'' e ''La'' são singulares, ''Los'' é masculino plural.","options":["El","La","Los","Las"],"prompt":"Completa la frase: ''___ universidades abren las puertas para los brasileños y los españoles.''"},{"answer_index":0,"explanation_pt_br":"Usamos ''El'' para ''portugués'' e ''español'' porque são substantivos masculinos e singulares. As outras opções não concordam em gênero ou número.","options":["El / El","La / La","Los / Los","Las / Las"],"prompt":"Completa la frase: ''___ portugués y ___ español tienen palabras iguales.''"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-7c71942a4c78', 'es', 'A1', 'Un día en el museo', 'El sábado, Ana y Pablo visitan el museo de arte moderno. La entrada es barata y los cuadros son muy bonitos. Ana mira un cuadro grande y dice: — ¡Qué obra tan interesante! Pablo prefiere las esculturas. Hay unas esculturas pequeñas y otras enormes. Los guías del museo explican la historia de cada obra.

Ana compra un libro y unos postales en la tienda. Pablo compra una gorra y dos camisetas para sus hijos. Al final, ellos comen en un restaurante cerca del museo. Las tapas son deliciosas y el café es bueno.

Ana y Pablo vuelven a casa contentos. Ellos piensan: — Mañana vamos a otro museo. ¿Cuál? Quizás el museo de ciencias naturales. ¡Allí hay dinosaurios! Pero Ana prefiere el museo de historia. Los dos están de acuerdo: el plan es perfecto.', '[{"answer_index":2,"explanation_pt_br":"Cuadros é uma palavra masculina no plural. Por isso, usamos o artigo definido \"los\". Em português seria \"os quadros\".","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo definido correcto para ''cuadros''?"},{"answer_index":0,"explanation_pt_br":"Escultura é um substantivo feminino. No singular, usamos \"la\". Portanto, \"la escultura\". As outras opções misturam gênero ou número.","options":["la escultura","el escultura","los esculturas","las escultura"],"prompt":"En el texto, ''las esculturas'' es femenino plural. ¿Cuál es la forma singular femenina?"},{"answer_index":0,"explanation_pt_br":"Una é o artigo indefinido feminino singular, como em \"una casa\". \"Un\" é masculino singular; \"unos\" e \"unas\" são plurais.","options":["una","unos","unas","un"],"prompt":"¿Cuál es el artículo indefinido femenino singular en español?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-a6dbc0f8cce3', 'es', 'A1', 'El español y el portugués', 'Brasil y España tienen una relación especial. El español y el portugués son lenguas parecidas. Muchos brasileños estudian el español en las escuelas. Los profesores dicen que es útil para viajar y trabajar.

En España hay muchas universidades. Algunos estudiantes brasileños viajan a Madrid o Barcelona. Un intercambio es una buena oportunidad. Las clases son interesantes y los estudiantes aprenden rápido. También hay muchos españoles en Brasil. Ellos viven en las ciudades grandes y trabajan en empresas.

La colaboración entre los dos países es importante. Un acuerdo educativo ayuda a los profesores y a los estudiantes. Los proyectos de intercambio son populares. El conocimiento científico es valioso. El portugués y el español no son una barrera, sino un puente.', '[{"answer_index":0,"explanation_pt_br":"Porque ''español'' é um substantivo masculino singular, e o artigo definido correspondente é ''el''.","options":["El","La","Los","Las"],"prompt":"Según el texto, ¿cuál es el artículo definido correcto para ''español''?"},{"answer_index":3,"explanation_pt_br":"''Escuelas'' é um substantivo feminino plural, então usamos ''las''.","options":["el","la","los","las"],"prompt":"Completa la frase con el artículo correcto: ''Muchos brasileños estudian en ___ escuelas.''"},{"answer_index":1,"explanation_pt_br":"''Oportunidad'' é um substantivo feminino singular, portanto usamos o artigo indefinido ''una''.","options":["Un","Una","Unos","Unas"],"prompt":"En la oración ''Un intercambio es una buena oportunidad'', ¿qué artículo acompaña a ''oportunidad''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-560120f01df0', 'es', 'A1', 'Un acuerdo entre países', 'El martes, los ministros de educación de Brasil y España firman un acuerdo. El acuerdo es para la cooperación en la educación. Los estudiantes y los profesores pueden viajar y estudiar en los dos países. Las universidades participan en los proyectos.

La lengua no es una barrera. El portugués y el español son idiomas muy cercanos. Los brasileños pueden entender el español, y los españoles pueden entender el portugués. Pero hay diferencias pequeñas.

Muchas personas viven en el país del otro. Unos brasileños viven en España, y unos españoles viven en Brasil. Las familias y las escuelas celebran la noticia. La educación es un puente entre las culturas.', '[{"answer_index":0,"explanation_pt_br":"No texto, ''los ministros'' indica um grupo plural masculino/misto. O artigo definido plural masculino é ''los'', e ''ministros'' termina em -s no plural.","options":["Los ministros","Las ministras","Un ministros","El ministros"],"prompt":"¿Quiénes firman el acuerdo?"},{"answer_index":0,"explanation_pt_br":"''Idiomas'' é masculino plural; ''cercanos'' concorda em gênero e número. A alternativa ''una idiomas'' tem artigo feminino e plural incorretos.","options":["Idiomas cercanos","Idioma cercano","Una idiomas","Las idioma"],"prompt":"¿Qué son el portugués y el español según el texto?"},{"answer_index":0,"explanation_pt_br":"''Universidades'' é feminino plural; o artigo definido apropriado é ''las''.","options":["Las","Los","El","Una"],"prompt":"Completa: ______ universidades participan en los proyectos."}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-590c34babcae', 'es', 'A1', 'La familia de Marta', 'Marta es una mujer española. Vive en Madrid con su familia. Su casa es grande y luminosa. En la casa hay tres habitaciones, dos baños y una cocina moderna. Marta tiene un hijo y una hija.

El hijo se llama Pablo y tiene diez años. La hija se llama Lucía y tiene ocho años. El padre de Marta se llama Juan y es un hombre simpático. La madre de Marta se llama Carmen y es una mujer trabajadora. Los abuelos viven cerca y visitan a la familia los domingos.

Los niños juegan en el parque con los amigos. El fin de semana, la familia come en un restaurante. Todos están felices.', '[{"answer_index":1,"explanation_pt_br":"A palavra ''casa'' é um substantivo feminino singular, por isso usamos o artigo definido ''la''.","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo correcto para la palabra ''casa''?"},{"answer_index":2,"explanation_pt_br":"A palavra ''niño'' é masculina, no plural fica ''niños'', e o artigo definido masculino plural é ''los''.","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo correcto para ''niños''?"},{"answer_index":1,"explanation_pt_br":"A palavra ''mujer'' é feminina singular, por isso usamos o artigo indefinido ''una''.","options":["un","una","unos","unas"],"prompt":"¿Cuál es el artículo indeterminado correcto para ''mujer''?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-b9030cf806c1', 'es', 'A1', 'Un acuerdo de educación entre Brasil y España', 'Brasil y España firman un acuerdo de educación. El ministro de Educación de Brasil y el embajador de España en Brasil firmaron un memorando. Los proyectos son para la formación de profesores y gestores. También hay programas de intercambio para estudiantes y profesores. Una profesora puede viajar a España, y un profesor puede viajar a Brasil. Las universidades brasileñas y españolas participan en el acuerdo.

Los estudiantes aprenden español en Brasil y portugués en España. El idioma no es una barrera porque las raíces lingüísticas son similares. Más de cien mil brasileños viven en España, y muchos españoles viven en Brasil. Este acuerdo es un motor para generar conocimiento científico.

La educación es importante para los dos países. Las familias brasileñas y españolas apoyan la idea. Los profesores están contentos con el acuerdo.', '[{"answer_index":3,"explanation_pt_br":"Universidades é um substantivo feminino e está no plural, por isso usamos o artigo definido feminino plural \"las\".","options":["el","la","los","las"],"prompt":"¿Cuál es el artículo definido para \"universidades\" en el texto?"},{"answer_index":0,"explanation_pt_br":"No masculino, o plural de \"un estudiante\" é \"unos estudiantes\". Em espanhol, usamos \"unos\" para masculino plural indefinido.","options":["unos estudiantes","unas estudiantes","los estudiante","las estudiante"],"prompt":"¿Cuál es el plural de \"un estudiante\"?"},{"answer_index":0,"explanation_pt_br":"\"Profesora\" é um substantivo feminino e está no singular, por isso usamos o artigo indefinido feminino singular \"una\".","options":["Es femenina singular","Es masculina singular","Es femenina plural","Es masculina plural"],"prompt":"En la frase \"Una profesora puede viajar a España\", ¿por qué usamos \"una\"?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-8ad630778c46', 'es', 'A1', 'La escuela de idiomas', 'En la escuela de idiomas hay muchos estudiantes. La biblioteca tiene muchos libros. Los profesores son de España y de Brasil. Una profesora habla español y un profesor habla portugués. Las clases son interesantes y los ejercicios son fáciles.

Hoy los estudiantes leen un libro. El libro tiene historias de América Latina. Las palabras son nuevas, pero los estudiantes usan el diccionario. Después, la clase habla de las vacaciones. Un estudiante quiere visitar Madrid, y una estudiante quiere conocer Buenos Aires.

Los estudiantes practican los artículos: el, la, los, las, un, una. El español es una lengua bonita y las lenguas son importantes.', '[{"answer_index":2,"explanation_pt_br":"O texto diz: ''Una profesora habla español y un profesor habla portugués.'' Portanto, quem fala português é ''un profesor'' (um professor).","options":["Una profesora","Los estudiantes","Un profesor","Las profesoras"],"prompt":"¿Quién habla portugués?"},{"answer_index":0,"explanation_pt_br":"O texto diz: ''Hoy los estudiantes leen un libro.'' Portanto, eles leem um livro.","options":["Un libro","Una revista","Los diccionarios","Las cartas"],"prompt":"¿Qué leen los estudiantes?"},{"answer_index":3,"explanation_pt_br":"No final do texto: ''Los estudiantes practican los artículos: el, la, los, las, un, una.'' Esses são os artículos definidos e indefinidos em espanhol.","options":["yo, tú, él, nosotros","uno, dos, tres, cuatro","en, de, con, para","el, la, los, las, un, una"],"prompt":"¿Cuáles son los artículos en español?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-4ee3e2856490', 'es', 'A1', 'En mi casa', '¡Hola! Me llamo Ana y vivo en una casa grande con mi familia. Mi padre es alto y mi madre es baja. Tengo un hermano y una hermana. Mi hermano tiene diez años y mi hermana tiene quince. En nuestra casa hay un perro pequeño y una gata negra. Los animales son muy simpáticos.

En mi casa hay tres habitaciones y dos baños. La cocina es blanca y el salón es cómodo. Las ventanas son grandes y los cuadros son bonitos. También hay un jardín con flores de colores.

Me gusta mucho mi casa porque es luminosa y tranquila. ¿Y tú? ¿Cómo es tu casa?', '[{"answer_index":0,"explanation_pt_br":"No texto, Ana diz: ''Tengo un hermano y una hermana'', ou seja, tem um irmão e uma irmã.","options":["Un hermano y una hermana","Dos hermanos","Dos hermanas","No tiene hermanos"],"prompt":"¿Cuántos hermanos tiene Ana?"},{"answer_index":0,"explanation_pt_br":"O texto afirma: ''La cocina es blanca''. Portanto, a cozinha é branca.","options":["Blanca","Negra","Grande","Cómoda"],"prompt":"¿Cómo es la cocina?"},{"answer_index":0,"explanation_pt_br":"Ana diz: ''hay un perro pequeño y una gata negra''. Assim, ela tem um cachorro e uma gata.","options":["Un perro y una gata","Dos perros","Una gata y un loro","Un pez y un perro"],"prompt":"¿Qué animales tiene Ana?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-6dd8012ad97a', 'es', 'A1', 'Las lenguas de España', 'Hoy en la clase de español, la profesora presenta un libro. El libro se llama ''Las lenguas de España''. En España hay una lengua oficial, el español, y también hay otras lenguas: el asturiano, el gallego y el catalán. Las lenguas son importantes para la cultura.

Los estudiantes leen un texto sobre un acuerdo entre Brasil y España. Los ministros firman unos documentos. El acuerdo es para la educación. Un profesor de Brasil y una profesora de España intercambian ideas. Los estudiantes aprenden con las palabras.

En español, los artículos tienen género y número. El y la son singulares; los y las son plurales. Un y una son indefinidos; unos y unas son plurales. Las palabras terminadas en -o son masculinas, y las terminadas en -a son femeninas. ¡Es una regla muy útil!', '[{"answer_index":0,"explanation_pt_br":"O artigo definido plural feminino em espanhol é ''las'' (por exemplo, las lenguas).","options":["las","los","la","el"],"prompt":"¿Cuál es el artículo definido plural femenino?"},{"answer_index":1,"explanation_pt_br":"''Un'' é o artigo indefinido singular masculino (por exemplo, un libro).","options":["el","un","los","una"],"prompt":"En el texto, ¿qué palabra es un artículo indefinido singular masculino?"},{"answer_index":1,"explanation_pt_br":"No texto, diz que as palavras terminadas em -a são femininas (por exemplo, lengua).","options":["-o","-a","-e","-s"],"prompt":"Según el texto, ¿cuál es la terminación de las palabras femeninas?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-92cf2820af04', 'es', 'A1', 'Un día de lenguas', 'La escuela de Ana organiza un día de lenguas. Los estudiantes de la clase de español participan con carteles, libros y banderas. Ana muestra un libro de cuentos. El libro es rojo y tiene muchas imágenes. Los estudiantes hablan de los países hispanohablantes. La maestra explica las diferencias entre el español y el portugués.

En el patio, las banderas de los países están en una mesa. Unos niños leen las palabras en español. Otros niños escriben frases en portugués. El director de la escuela abre el evento con un discurso. Dice: "Las lenguas son importantes para la comunicación y la cultura".

Al final, los estudiantes reciben un certificado. La clase de Ana gana un premio por el mejor cartel. Todos están felices porque aprenden algo nuevo sobre las palabras y los idiomas.', '[{"answer_index":0,"explanation_pt_br":"O texto diz: ''Ana muestra un libro de cuentos.'' Por isso, a resposta correta é ''Un libro de cuentos''.","options":["Un libro de cuentos","Una bandera","Un certificado","Un cartel"],"prompt":"¿Qué muestra Ana en el día de lenguas?"},{"answer_index":1,"explanation_pt_br":"O texto diz: ''El libro es rojo y tiene muchas imágenes.'' Portanto, ''rojo'' é a cor do livro.","options":["Azul","Rojo","Verde","Amarillo"],"prompt":"¿Cómo es el libro de Ana?"},{"answer_index":0,"explanation_pt_br":"''Banderas'' é um substantivo feminino plural, por isso usamos ''las'' como artigo definido feminino plural (las banderas).","options":["las","los","un","el"],"prompt":"En la frase ''Las banderas de los países están en una mesa'', ¿cuál es el artículo femenino plural?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-es-a1-6546f5a4dc89', 'es', 'A1', 'Un acuerdo entre Brasil y España', 'Brasil y España firman un acuerdo de educación. El ministro de Educación de Brasil y el embajador de España participan en la ceremonia. Los dos países quieren compartir sus conocimientos. El acuerdo incluye programas de intercambio para estudiantes y profesores. Muchos españoles viven en Brasil y muchos brasileños viven en España. El idioma no es una barrera. Las universidades tienen proyectos nuevos. Los profesores pueden trabajar juntos en investigaciones. Los estudiantes pueden aprender en otro país. Es una oportunidad única para la ciencia y la cultura.

El acuerdo también incluye seminarios y conferencias. Los investigadores pueden compartir ideas. Los programas son para estudiantes de licenciatura, máster y doctorado. Las instituciones educativas están contentas con el plan. El memorando fue firmado en 2018. La colaboración continúa hoy. Los jóvenes tienen más opciones para su futuro. Las familias pueden acompañar a sus hijos en esta experiencia.', '[{"answer_index":0,"explanation_pt_br":"A palavra ''oportunidad'' é feminina, por isso o plural correto é ''las oportunidades''.","options":["las oportunidades","los oportunidades","la oportunidad","las oportunidads"],"prompt":"¿Cuál es el plural de ''la oportunidad''?"},{"answer_index":1,"explanation_pt_br":"A palavra ''estudiantes'' é plural e usa-se o artigo masculino plural ''los'' para se referir a um grupo geral.","options":["El","Los","La","Las"],"prompt":"Complete con el artículo correcto: ''____ estudiantes son inteligentes.''"},{"answer_index":1,"explanation_pt_br":"A palavra ''acuerdo'' é masculina singular, portanto o artigo correto é ''el''.","options":["La acuerdo es importante.","El acuerdo es importante.","Los acuerdo son importantes.","Las acuerdo son importantes."],"prompt":"¿Qué frase tiene el artículo definido correcto?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();
