-- GENERATED FILE: review source provenance and content before applying.
-- Content is unpublished unless --publish was explicitly used.

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-b79790e365d7', 'fr', 'A1', 'La famille Martin au marché', 'Le samedi matin, la famille Martin va au marché. Le père achète des pommes et des oranges. La mère achète du pain et un gâteau. Le frère et la sœur regardent les animaux. Il y a des chiens, des chats et un lapin. Les enfants aiment les animaux.

Au marché, il y a beaucoup de personnes. Un homme vend des légumes. Une femme vend des fleurs. Les légumes sont verts et les fleurs sont jolies. La sœur veut des fleurs. Le frère veut un chien. Le père dit non.

Après le marché, la famille rentre à la maison. Ils préparent un repas avec les légumes et le pain. Le gâteau est pour le dessert. C''est une belle journée.', '[{"answer_index":2,"explanation_pt_br":"Pommes é um substantivo feminino no plural, portanto usamos o artigo indefinido plural ''des''. No texto: ''Le père achète des pommes.''","options":["un","une","des","le"],"prompt":"Complétez avec l''article correct : « Le père achète ___ pommes. »"},{"answer_index":0,"explanation_pt_br":"Pain é um substantivo masculino singular. Usamos a contração ''du'' (de + le). No texto: ''La mère achète du pain.''","options":["du","de la","des","les"],"prompt":"Complétez avec l''article correct : « La mère achète ___ pain. »"},{"answer_index":2,"explanation_pt_br":"A palavra ''fleur'' é feminina singular: ''une fleur''. As outras palavras são masculinas: le chien, le gâteau, le marché.","options":["chien","gâteau","fleur","marché"],"prompt":"Dans le texte, quel mot est féminin singulier ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-6c59390cc2b7', 'fr', 'A1', 'Ma famille et le parc', 'Bonjour ! Je m''appelle Marie. Voici ma famille. Mon père s''appelle Jean. Ma mère s''appelle Sophie. J''ai un frère et une sœur. Mon frère a un vélo et ma sœur a une poupée. Nous avons aussi un chat noir et une souris blanche. Le chat adore la souris, mais la souris a peur du chat !

Aujourd''hui, nous allons au parc. Dans le parc, il y a des arbres et des fleurs. Les arbres sont grands. Les fleurs sont belles. Je vois un oiseau et une fleur rouge. L''oiseau chante. J''aime le parc !

Les enfants jouent dans le parc. Un garçon lance un ballon. Une fille lit une histoire. Les oiseaux chantent. C''est une belle journée !', '[{"answer_index":0,"explanation_pt_br":"O texto diz: ''Je vois un oiseau et une fleur rouge.''","options":["Un oiseau et une fleur rouge","Un chat et une souris","Un vélo et une poupée","Un ballon et une histoire"],"prompt":"Qu''est-ce que Marie voit dans le parc ?"},{"answer_index":0,"explanation_pt_br":"O texto diz: ''Un garçon lance un ballon.''","options":["Un garçon","Une fille","Un oiseau","Le chat"],"prompt":"Qui lance un ballon ?"},{"answer_index":0,"explanation_pt_br":"O texto diz: ''Le chat adore la souris, mais la souris a peur du chat !''","options":["La souris","Le parc","La fleur","Le vélo"],"prompt":"Le chat adore quoi ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-d2c376639c70', 'fr', 'A1', 'Ma famille', 'Je m’appelle Lucas. J’ai une petite famille. Mon père s’appelle Paulo et ma mère s’appelle Ana. J’ai un frère et une sœur. Mon frère est grand et ma sœur est petite. Nous avons un chien et un chat. Le chien s’appelle Rex et le chat s’appelle Mina.

Dans notre maison, il y a des chambres, une cuisine, un salon et une salle de bain. Les chambres sont bleues. La cuisine est blanche. Le salon est jaune. La salle de bain est verte. Nous aimons les repas ensemble. Le soir, nous regardons des films. Les films sont amusants. J’aime ma famille.', '[{"answer_index":0,"explanation_pt_br":"A palavra ''frère'' é masculina e singular, portanto usamos o artigo indefinido ''un''.","options":["un","une","des","le"],"prompt":"Complétez la phrase : « J’ai ___ frère. »"},{"answer_index":1,"explanation_pt_br":"A palavra ''sœur'' é feminina e singular, portanto usamos o artigo definido ''la''.","options":["Le","La","Les","Un"],"prompt":"Complétez la phrase : « ___ sœur s’appelle Ana. »"},{"answer_index":1,"explanation_pt_br":"''Chambres'' é feminino e plural, então o adjetivo concorda em gênero e número: ''bleues''.","options":["Les chambres sont bleus.","Les chambres sont bleues.","La chambre sont bleue.","Le chambres sont bleues."],"prompt":"Quelle phrase est correcte ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-0299d20c015a', 'fr', 'A1', 'Au marché', 'Marie habite à Paris. Samedi, elle va au marché avec son ami Paul. Ils achètent des fruits et des légumes. Marie adore les bananes. Elle voit des bananes jaunes et des pommes vertes. Elle achète une pomme et un pain. Le pain est frais.

Paul achète des tomates et des carottes. Les tomates sont rouges, mais les carottes sont orange. Le vendeur est très sympa. Il donne un sac à Marie. Le sac est grand et solide. Marie met les fruits et les légumes dans le sac. Elle est heureuse. Paul et Marie rentrent à la maison.

Ils préparent une salade avec les tomates et les carottes. Marie mange la pomme. C''est bon!', '[{"answer_index":1,"explanation_pt_br":"Pomme é feminino singular; usamos une (indefinido). Un é masculino, des é plural, le é definido singular masculino.","options":["un","une","des","le"],"prompt":"Complétez avec le bon article : Marie achète ___ pomme."},{"answer_index":2,"explanation_pt_br":"Pain é masculino singular (le pain). Os outros estão no feminino ou no plural.","options":["bananes","carottes","pain","pommes"],"prompt":"Dans le texte, quel mot est au masculin singulier ?"},{"answer_index":2,"explanation_pt_br":"Fruits é o plural de fruit (masculino). O artigo indefinido plural é des para ambos os gêneros.","options":["Parce que fruits est masculin singulier","Parce que fruits est féminin pluriel","Parce que fruits est masculin pluriel","Parce que fruits est féminin singulier"],"prompt":"Pourquoi l''article « des » est-il utilisé dans « des fruits » ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-c82cc7f8f6b7', 'fr', 'A1', 'Les élections des délégués', 'Marie et Paul sont dans la même classe. Aujourd''hui, il y a les élections des délégués. Marie est une candidate. Paul est un candidat. Les élèves vont voter pour un garçon ou pour une fille.

Le directeur ouvre la salle. Des affiches sont sur les murs. Les bulletins sont sur une grande table. Le professeur explique le vote : chaque élève prend un bulletin et écrit un nom.

Marie parle : « Je veux une école propre et des activités pour tous. » Paul dit : « Je propose des sports et une bibliothèque. » Après le vote, le professeur compte les voix. Marie gagne ! Elle est contente. Les élèves applaudissent.', '[{"answer_index":1,"explanation_pt_br":"« candidate » é um substantivo feminino singular, por isso usamos o artigo indefinido feminino « une ».","options":["un","une","des","le"],"prompt":"Complète avec l''article correct : « Marie est ___ candidate. »"},{"answer_index":2,"explanation_pt_br":"« élèves » é plural (masculino ou misto). O artigo definido plural é « les ».","options":["La","Le","Les","Un"],"prompt":"Complète avec l''article correct : « ___ élèves vont voter. »"},{"answer_index":3,"explanation_pt_br":"No texto, Paul não especifica quais esportes, então usamos o artigo indefinido plural « des ».","options":["un","une","les","des"],"prompt":"Complète : « Paul propose ___ sports. »"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();
