-- GENERATED FILE: review source provenance and content before applying.
-- Content is unpublished unless --publish was explicitly used.

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-77dcbdfd1a2c', 'fr', 'A1', 'Au marché', 'Le samedi, Marie et Lucas vont au marché. Ils achètent des fruits et des légumes. Marie prend une pomme verte et une banane jaune. Lucas regarde les tomates rouges et les fromages. Le marché est grand et coloré.

La sœur de Lucas s’appelle Julie. Elle a un chien noir et une chatte blanche. Les animaux sont mignons. Julie achète des fleurs pour sa mère. Elle donne les fleurs à sa mère. La mère dit merci avec un sourire.

Après le marché, ils rentrent à la maison. Lucas prépare un gâteau avec les pommes. Les enfants sont contents. Ils aiment le marché et les produits frais.', '[{"answer_index":0,"explanation_pt_br":"Porque « pomme » e « banane » são substantivos femininos. Por isso usamos o artigo indefinido feminino singular « une ».","options":["parce que « pomme » et « banane » sont des noms féminins","parce que c''est au pluriel","parce que ce sont des noms masculins","parce que c''est le même article pour tous les noms"],"prompt":"Dans le texte, on lit « une pomme » et « une banane ». Pourquoi utilise-t-on « une » ?"},{"answer_index":0,"explanation_pt_br":"O plural de « un chien » é « des chiens »: usamos o artigo indefinido plural « des » e acrescentamos -s ao substantivo.","options":["des chiens","un chiens","une chien","le chiens"],"prompt":"Quel est le pluriel de « un chien » ?"},{"answer_index":0,"explanation_pt_br":"Usamos o artigo definido plural « les » para substantivos no plural. « Animaux » é masculino plural.","options":["parce que « animaux » est masculin pluriel","parce que « animaux » est féminin singulier","parce que c''est toujours « les » au singulier","parce que « animaux » est un nom propre"],"prompt":"Dans la phrase « Les animaux sont mignons », pourquoi utilise-t-on « les » ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-34a4702b57fd', 'fr', 'A1', 'Dans la salle de classe', 'Bonjour ! Je m’appelle Marie. Voici ma classe. C’est une salle de classe. Sur la table, il y a un livre, une règle et des cahiers. Le livre est rouge. La règle est bleue. Les cahiers sont verts. J’ai aussi un sac bleu. Dans le sac, il y a une trousse, des crayons et un cahier.

Dans la classe, il y a des élèves. Le garçon s’appelle Paul. La fille s’appelle Léa. Ils ont des amis. Les amis sont sympas. Le professeur est madame Dupont. Elle est gentille. Les élèves écoutent la leçon. Paul a un stylo. Léa a une gomme. Les stylos sont noirs. Les gommes sont blanches.

Maintenant, je regarde la porte. La porte est marron. Le tableau est noir. Les fenêtres sont grandes. Le sol est gris. J’aime ma classe !', '[{"answer_index":0,"explanation_pt_br":"« Livre » é um substantivo masculino singular, então o artigo definido correto é « le » (o). A frase significa: o livro é vermelho.","options":["Le","La","Les","Une"],"prompt":"Complétez : ______ livre est rouge."},{"answer_index":1,"explanation_pt_br":"« Règle » é um substantivo feminino singular, então usamos « la » (a). A frase significa: a régua é azul.","options":["Le","La","Les","Des"],"prompt":"Complétez : ______ règle est bleue."},{"answer_index":2,"explanation_pt_br":"« Cahiers » está no plural, então o artigo definido plural é « les » (os). A frase significa: os cadernos são verdes.","options":["Le","La","Les","Des"],"prompt":"Complétez : ______ cahiers sont verts."}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-7e0d8b4cf31c', 'fr', 'A1', 'Une belle journée au parc', 'Voici Marie et Paul. Ils sont dans un parc. Le parc est joli. Il y a un grand arbre, une petite fleur et des oiseaux. Marie montre un chien. Le chien est noir. Paul regarde les enfants qui jouent au ballon.

Après le parc, ils vont à la boulangerie. Marie achète une baguette et des croissants. Paul préfère le pain au chocolat. La boulangère est gentille. Elle donne un bonbon à Paul. Il dit merci.

Le soir, ils rentrent à la maison. Ils allument la télévision et regardent un film. Le film est amusant. Ils mangent des gâteaux. Quelle belle journée !', '[{"answer_index":0,"explanation_pt_br":"O texto diz: ''Il y a un grand arbre, une petite fleur et des oiseaux.'' As outras opções mencionam elementos que não aparecem (chat, maison) ou o chien, que está em outra frase.","options":["Un grand arbre, une petite fleur et des oiseaux.","Un grand chat, une petite fleur et des oiseaux.","Un grand arbre, une petite maison et des oiseaux.","Un grand arbre, une petite fleur et un chien."],"prompt":"Dans le parc, qu''est-ce qu''il y a ?"},{"answer_index":0,"explanation_pt_br":"No texto: ''Marie achète une baguette et des croissants.'' As opções 2, 3 e 4 não correspondem ao que Marie faz na boulangerie.","options":["Elle achète une baguette et des croissants.","Elle achète un pain et des bonbons.","Elle regarde les enfants jouer.","Elle donne un bonbon à Paul."],"prompt":"Que fait Marie à la boulangerie ?"},{"answer_index":0,"explanation_pt_br":"''Le film'' é masculino singular, por isso o adjetivo concorda no masculino singular: ''Il est amusant''. As outras opções usam feminino ou plural.","options":["Il est amusant.","Elle est amusante.","Ils sont amusants.","Elles sont amusantes."],"prompt":"Comment est le film ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-a11aa8159f19', 'fr', 'A1', 'Ma famille et mes animaux', 'Salut ! Je m''appelle Lucas. Voici ma famille. Mon père est un professeur. Ma mère est une infirmière. Ils ont un fils et une fille. Le fils s''appelle Tom et la fille s''appelle Léa. Nous avons des animaux : un chien et une chatte.

Le chien est grand et la chatte est petite. Les chiens aiment les os. Les chats aiment le lait. Dans la maison, il y a des livres et des jouets. Le livre de Tom est rouge. Le jouet de Léa est bleu.

Ma mère a une voiture bleue. Le père de mon ami a un vélo. Les voitures sont dans le garage. Les vélos sont dans le jardin. Voilà ma famille et mes animaux !', '[{"answer_index":0,"explanation_pt_br":"No texto, ''un'' é usado antes de ''chien'' porque ''chien'' é um substantivo masculino; ''une'' antes de ''chatte'' porque ''chatte'' é feminino.","options":["« Chien » est masculin et « chatte » est féminin.","« Chien » est pluriel et « chatte » est singulier.","« Chien » commence par une consonne et « chatte » par une voyelle.","L''auteur a fait une erreur."],"prompt":"Dans le texte, on lit « un chien » et « une chatte ». Pourquoi les articles sont différents ?"},{"answer_index":0,"explanation_pt_br":"O plural de ''un livre'' é ''des livres'', pois o artigo indefinido plural é ''des''.","options":["des livres","un livres","le livres","une livres"],"prompt":"Quelle est la forme plurielle de « un livre » ?"},{"answer_index":0,"explanation_pt_br":"O artigo definido plural é ''les'' para masculino e feminino; ''voitures'' é um substantivo feminino plural.","options":["Parce que « voitures » est féminin pluriel.","Parce que « voitures » est masculin singulier.","Parce que « voitures » est féminin singulier.","Parce que « voitures » est masculin pluriel."],"prompt":"Dans la phrase « Les voitures sont dans le garage », pourquoi utilise-t-on « les » ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-24ccca7509a6', 'fr', 'A1', 'Ma famille et ma maison', 'Salut ! Je m''appelle Lucas. Voici ma famille. Mon père est médecin et ma mère est professeure. J''ai un frère et une sœur. Mon frère s''appelle Tom. Ma sœur s''appelle Lina. Nous avons aussi des animaux : un chat et une tortue. Le chat s''appelle Minou et la tortue s''appelle Tico.

Dans ma maison, il y a des chambres, une cuisine et un salon. La cuisine est grande. Les chambres sont petites. Il y a aussi un jardin avec des fleurs et des arbres. J''aime le jardin. Ma sœur aime les fleurs. Mon frère préfère les jeux vidéo.

Ma famille est sympa. Nous sommes heureux. Et toi, ta famille est comment ?', '[{"answer_index":0,"explanation_pt_br":"Em francês, ''frère'' (irmão) é masculino singular, então usamos ''un'' (um). ''Sœur'' (irmã) é feminino singular, então usamos ''une'' (uma). ''le/la'' são artigos definidos singulares e ''des'' é plural.","options":["un / une","une / un","le / la","des / des"],"prompt":"Complétez avec les articles corrects : « J''ai ___ frère et ___ sœur. »"},{"answer_index":0,"explanation_pt_br":"''Les'' é o artigo definido para o plural em francês, tanto para masculino quanto para feminino. Como ''chambres'' (quartos) está no plural, usamos ''les''.","options":["Parce que ''chambres'' est au pluriel.","Parce que ''chambres'' est féminin.","Parce que ''chambres'' est masculin.","Parce que ''chambres'' est singulier."],"prompt":"Pourquoi le texte utilise-t-il « les chambres » ?"},{"answer_index":0,"explanation_pt_br":"''Fleurs'' (flores) é feminino plural. Precisamos do artigo plural ''les'' e do verbo no plural ''sont''. ''La'' é feminino singular, ''le'' é masculino singular e ''un'' é masculino singular.","options":["Les fleurs sont belles.","La fleurs sont belles.","Le fleurs sont belles.","Un fleurs est belle."],"prompt":"Quelle phrase est correcte ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-dd8b393053d9', 'fr', 'A1', 'Ma famille et ma chambre', 'Voici ma famille. Mon père s''appelle Marc. C''est un homme gentil. Ma mère s''appelle Julie. C''est une femme intelligente. J''ai un frère et une sœur. Le frère s''appelle Paul et la sœur s''appelle Anna. Nous avons aussi un chat noir et une chienne blanche. Les animaux sont petits.

Nous aimons les livres et les films. Dans ma chambre, il y a un lit, une table, des chaises et une fenêtre. Les murs sont jaunes. Le matin, je mange une pomme et je bois un café. La pomme est verte. Le café est chaud. Ma sœur Anna a des amies brésiliennes. Elles sont sympa.', '[{"answer_index":0,"explanation_pt_br":"Em francês, o substantivo ''frère'' (irmão) é masculino singular, por isso usamos o artigo indefinido ''un''. Já ''sœur'' (irmã) é feminino singular, e usamos ''une''. Portanto, a opção correta é ''un / une''.","options":["un / une","une / un","le / la","des / des"],"prompt":"Complétez la phrase : « J''ai ______ frère et ______ sœur. »"},{"answer_index":2,"explanation_pt_br":"O substantivo ''animaux'' está no plural e é masculino. O artigo definido plural é ''les'', para masculino e feminino. ''Le'' e ''la'' são singulares, e ''des'' é artigo indefinido. Então, ''Les animaux sont petits'' é correto.","options":["le","la","les","des"],"prompt":"Choisissez l''article défini correct pour le mot « animaux » : ______ animaux sont petits."},{"answer_index":0,"explanation_pt_br":"''Pomme'' é um substantivo feminino singular, então exige o artigo definido feminino ''la''. A frase ''La pomme est verte'' está correta. As outras opções têm erro de gênero ou de concordância no plural.","options":["La pomme est verte.","Le pomme est verte.","Une pomme sont vertes.","Les pomme est verte."],"prompt":"Quelle phrase est correcte ?"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();

insert into public.reading_passages (id, language, level, title, body, questions, sort_order, is_published)
values ('generated-reading-fr-a1-bbf72474596e', 'fr', 'A1', 'Les élections dans un pays', 'Aujourd''hui, c''est un jour spécial. Il y a une élection importante dans le pays. Les électeurs vont voter pour choisir un nouveau gouvernement. Dans la ville, il y a des affiches et des drapeaux. Les journalistes sont présents. Ils parlent avec les citoyens.

Le premier ministre est content. Il dit : « Les citoyens sont contents. » Une femme attend devant une école. Elle a un enfant. Elle parle à un journaliste. Elle dit : « Je vote pour l''éducation et la santé. » Des hommes discutent dans un café. Ils regardent les résultats sur un téléphone.

À la fin de la journée, les résultats arrivent. Le parti du premier ministre gagne. Les personnes dans la rue sont heureuses. Une jeune fille dit : « C''est une bonne nouvelle pour le pays. » Les gens espèrent un avenir meilleur.', '[{"answer_index":1,"explanation_pt_br":"''Élection'' é uma palavra feminina. Para falar ''uma eleição'', usamos o artigo indefinido feminino ''une''. As outras opções: ''un'' (masculino), ''des'' (plural), ''le'' (definido masculino).","options":["un","une","des","le"],"prompt":"Complétez la phrase : « Aujourd''hui, il y a ___ élection importante. »"},{"answer_index":0,"explanation_pt_br":"''Les'' é o artigo definido plural em francês, usado para ''os'' ou ''as''. ''Les électeurs'' significa ''os eleitores''. As outras opções usam artigos indefinidos ou contração: ''un gouvernement'' (um governo), ''une école'' (uma escola), ''du premier ministre'' (do primeiro-ministro).","options":["les électeurs","un gouvernement","une école","du premier ministre"],"prompt":"Dans le texte, quelle phrase utilise correctement un article défini pluriel ?"},{"answer_index":0,"explanation_pt_br":"''Café'' é um substantivo masculino singular, então o artigo indefinido correto é ''un''. ''Une'' é feminino, ''des'' é plural e ''la'' é definido feminino.","options":["un café","une rue","des hommes","la santé"],"prompt":"Choisissez la phrase correcte avec un article indéfini masculin singulier :"}]'::jsonb, 0, true)
on conflict (id) do update set title=excluded.title, body=excluded.body, questions=excluded.questions, is_published=excluded.is_published, updated_at=now();
